### ISSUE TITLE
Configuring this into a existing Icinga2-director

### ISSUE THREAD

**Issue by noudAndi** [konstantin-kelemen/icinga2-pushbullet-notifications#1]
Hi,

at the time of writing, Iicinga2-director doesn't have the ability to manage "env" Variable in Notification Commands.

https://github.com/Icinga/icingaweb2-module-director/issues/256

How did you manage to configure this, while having Icingaweb2 installed?

Cheers
Andi

**Comment by konstantin-kelemen** [comment]
Hi, @noudAndi!

The variables are being defined in conf.d/commands.conf and then passed to the bash script.

You don't have to manage them in Icinga Director/Icinga Web 2.

**Comment by noudAndi** [comment]
Hi @konstantin-kelemen,

I solved it by importing the configuration via "Import source". 

"Source type" : Core API" 
"Object type": "Notification Commands"

Thanks! @konstantin-kelemen 

Cheers
Andi
